/**
 * AUTO-GENERATED by scripts/generate-event-icons.ts.
 *
 * Do not edit by hand. To add or modify an event icon, update the
 * SPECS array in the generator and re-run `tsx scripts/generate-event-icons.ts`.
 *
 * Each loader does a dynamic `import(?raw)` of the icon + annotation
 * SVG strings so Vite emits a per-event chunk; consumers (EventIcon
 * via React.lazy) never load all 40 up front.
 *
 * Phase 5 — Margin Notes UI Redesign (P5.1, P5.5)
 */

import { CrazyEvent } from '../../engine/types';
import type { EventIconLoader } from '../eventData';

export const EVENT_ICON_LOADERS: Readonly<Partial<Record<CrazyEvent, EventIconLoader>>> = {
  [CrazyEvent.KingForADay]: async () => {
    const [icon, annotation, metadata] = await Promise.all([
      import('./king-for-a-day.svg?raw'),
      import('./king-for-a-day.annotation.svg?raw'),
      import('./king-for-a-day.metadata.json'),
    ]);
    return {
      icon: icon.default,
      annotation: annotation.default,
      drawOnDurationMs: (metadata.default as { drawOnDurationMs: number }).drawOnDurationMs,
    };
  },
  [CrazyEvent.LiveGrenade]: async () => {
    const [icon, annotation, metadata] = await Promise.all([
      import('./live-grenade.svg?raw'),
      import('./live-grenade.annotation.svg?raw'),
      import('./live-grenade.metadata.json'),
    ]);
    return {
      icon: icon.default,
      annotation: annotation.default,
      drawOnDurationMs: (metadata.default as { drawOnDurationMs: number }).drawOnDurationMs,
    };
  },
  [CrazyEvent.HotPotato]: async () => {
    const [icon, annotation, metadata] = await Promise.all([
      import('./hot-potato.svg?raw'),
      import('./hot-potato.annotation.svg?raw'),
      import('./hot-potato.metadata.json'),
    ]);
    return {
      icon: icon.default,
      annotation: annotation.default,
      drawOnDurationMs: (metadata.default as { drawOnDurationMs: number }).drawOnDurationMs,
    };
  },
  [CrazyEvent.ChecksMix]: async () => {
    const [icon, annotation, metadata] = await Promise.all([
      import('./checks-mix.svg?raw'),
      import('./checks-mix.annotation.svg?raw'),
      import('./checks-mix.metadata.json'),
    ]);
    return {
      icon: icon.default,
      annotation: annotation.default,
      drawOnDurationMs: (metadata.default as { drawOnDurationMs: number }).drawOnDurationMs,
    };
  },
  [CrazyEvent.OppositeDay]: async () => {
    const [icon, annotation, metadata] = await Promise.all([
      import('./opposite-day.svg?raw'),
      import('./opposite-day.annotation.svg?raw'),
      import('./opposite-day.metadata.json'),
    ]);
    return {
      icon: icon.default,
      annotation: annotation.default,
      drawOnDurationMs: (metadata.default as { drawOnDurationMs: number }).drawOnDurationMs,
    };
  },
  [CrazyEvent.UpInTheAir]: async () => {
    const [icon, annotation, metadata] = await Promise.all([
      import('./up-in-the-air.svg?raw'),
      import('./up-in-the-air.annotation.svg?raw'),
      import('./up-in-the-air.metadata.json'),
    ]);
    return {
      icon: icon.default,
      annotation: annotation.default,
      drawOnDurationMs: (metadata.default as { drawOnDurationMs: number }).drawOnDurationMs,
    };
  },
  [CrazyEvent.NoTouching]: async () => {
    const [icon, annotation, metadata] = await Promise.all([
      import('./no-touching.svg?raw'),
      import('./no-touching.annotation.svg?raw'),
      import('./no-touching.metadata.json'),
    ]);
    return {
      icon: icon.default,
      annotation: annotation.default,
      drawOnDurationMs: (metadata.default as { drawOnDurationMs: number }).drawOnDurationMs,
    };
  },
  [CrazyEvent.StepBack]: async () => {
    const [icon, annotation, metadata] = await Promise.all([
      import('./step-back.svg?raw'),
      import('./step-back.annotation.svg?raw'),
      import('./step-back.metadata.json'),
    ]);
    return {
      icon: icon.default,
      annotation: annotation.default,
      drawOnDurationMs: (metadata.default as { drawOnDurationMs: number }).drawOnDurationMs,
    };
  },
  [CrazyEvent.FlippedScript]: async () => {
    const [icon, annotation, metadata] = await Promise.all([
      import('./flipped-script.svg?raw'),
      import('./flipped-script.annotation.svg?raw'),
      import('./flipped-script.metadata.json'),
    ]);
    return {
      icon: icon.default,
      annotation: annotation.default,
      drawOnDurationMs: (metadata.default as { drawOnDurationMs: number }).drawOnDurationMs,
    };
  },
  [CrazyEvent.MarchingOrders]: async () => {
    const [icon, annotation, metadata] = await Promise.all([
      import('./marching-orders.svg?raw'),
      import('./marching-orders.annotation.svg?raw'),
      import('./marching-orders.metadata.json'),
    ]);
    return {
      icon: icon.default,
      annotation: annotation.default,
      drawOnDurationMs: (metadata.default as { drawOnDurationMs: number }).drawOnDurationMs,
    };
  },
  [CrazyEvent.DealersChoice]: async () => {
    const [icon, annotation, metadata] = await Promise.all([
      import('./dealers-choice.svg?raw'),
      import('./dealers-choice.annotation.svg?raw'),
      import('./dealers-choice.metadata.json'),
    ]);
    return {
      icon: icon.default,
      annotation: annotation.default,
      drawOnDurationMs: (metadata.default as { drawOnDurationMs: number }).drawOnDurationMs,
    };
  },
  [CrazyEvent.Bodyguard]: async () => {
    const [icon, annotation, metadata] = await Promise.all([
      import('./bodyguard.svg?raw'),
      import('./bodyguard.annotation.svg?raw'),
      import('./bodyguard.metadata.json'),
    ]);
    return {
      icon: icon.default,
      annotation: annotation.default,
      drawOnDurationMs: (metadata.default as { drawOnDurationMs: number }).drawOnDurationMs,
    };
  },
  [CrazyEvent.Quicksand]: async () => {
    const [icon, annotation, metadata] = await Promise.all([
      import('./quicksand.svg?raw'),
      import('./quicksand.annotation.svg?raw'),
      import('./quicksand.metadata.json'),
    ]);
    return {
      icon: icon.default,
      annotation: annotation.default,
      drawOnDurationMs: (metadata.default as { drawOnDurationMs: number }).drawOnDurationMs,
    };
  },
  [CrazyEvent.Conscription]: async () => {
    const [icon, annotation, metadata] = await Promise.all([
      import('./conscription.svg?raw'),
      import('./conscription.annotation.svg?raw'),
      import('./conscription.metadata.json'),
    ]);
    return {
      icon: icon.default,
      annotation: annotation.default,
      drawOnDurationMs: (metadata.default as { drawOnDurationMs: number }).drawOnDurationMs,
    };
  },
  [CrazyEvent.GhostWalk]: async () => {
    const [icon, annotation, metadata] = await Promise.all([
      import('./ghost-walk.svg?raw'),
      import('./ghost-walk.annotation.svg?raw'),
      import('./ghost-walk.metadata.json'),
    ]);
    return {
      icon: icon.default,
      annotation: annotation.default,
      drawOnDurationMs: (metadata.default as { drawOnDurationMs: number }).drawOnDurationMs,
    };
  },
  [CrazyEvent.Landmine]: async () => {
    const [icon, annotation, metadata] = await Promise.all([
      import('./landmine.svg?raw'),
      import('./landmine.annotation.svg?raw'),
      import('./landmine.metadata.json'),
    ]);
    return {
      icon: icon.default,
      annotation: annotation.default,
      drawOnDurationMs: (metadata.default as { drawOnDurationMs: number }).drawOnDurationMs,
    };
  },
  [CrazyEvent.Leapfrog]: async () => {
    const [icon, annotation, metadata] = await Promise.all([
      import('./leapfrog.svg?raw'),
      import('./leapfrog.annotation.svg?raw'),
      import('./leapfrog.metadata.json'),
    ]);
    return {
      icon: icon.default,
      annotation: annotation.default,
      drawOnDurationMs: (metadata.default as { drawOnDurationMs: number }).drawOnDurationMs,
    };
  },
  [CrazyEvent.FrozenAssets]: async () => {
    const [icon, annotation, metadata] = await Promise.all([
      import('./frozen-assets.svg?raw'),
      import('./frozen-assets.annotation.svg?raw'),
      import('./frozen-assets.metadata.json'),
    ]);
    return {
      icon: icon.default,
      annotation: annotation.default,
      drawOnDurationMs: (metadata.default as { drawOnDurationMs: number }).drawOnDurationMs,
    };
  },
  [CrazyEvent.DoubleTime]: async () => {
    const [icon, annotation, metadata] = await Promise.all([
      import('./double-time.svg?raw'),
      import('./double-time.annotation.svg?raw'),
      import('./double-time.metadata.json'),
    ]);
    return {
      icon: icon.default,
      annotation: annotation.default,
      drawOnDurationMs: (metadata.default as { drawOnDurationMs: number }).drawOnDurationMs,
    };
  },
  [CrazyEvent.SafeHaven]: async () => {
    const [icon, annotation, metadata] = await Promise.all([
      import('./safe-haven.svg?raw'),
      import('./safe-haven.annotation.svg?raw'),
      import('./safe-haven.metadata.json'),
    ]);
    return {
      icon: icon.default,
      annotation: annotation.default,
      drawOnDurationMs: (metadata.default as { drawOnDurationMs: number }).drawOnDurationMs,
    };
  },
  [CrazyEvent.ChainReaction]: async () => {
    const [icon, annotation, metadata] = await Promise.all([
      import('./chain-reaction.svg?raw'),
      import('./chain-reaction.annotation.svg?raw'),
      import('./chain-reaction.metadata.json'),
    ]);
    return {
      icon: icon.default,
      annotation: annotation.default,
      drawOnDurationMs: (metadata.default as { drawOnDurationMs: number }).drawOnDurationMs,
    };
  },
  [CrazyEvent.PromotionParty]: async () => {
    const [icon, annotation, metadata] = await Promise.all([
      import('./promotion-party.svg?raw'),
      import('./promotion-party.annotation.svg?raw'),
      import('./promotion-party.metadata.json'),
    ]);
    return {
      icon: icon.default,
      annotation: annotation.default,
      drawOnDurationMs: (metadata.default as { drawOnDurationMs: number }).drawOnDurationMs,
    };
  },
  [CrazyEvent.Reinforcements]: async () => {
    const [icon, annotation, metadata] = await Promise.all([
      import('./reinforcements.svg?raw'),
      import('./reinforcements.annotation.svg?raw'),
      import('./reinforcements.metadata.json'),
    ]);
    return {
      icon: icon.default,
      annotation: annotation.default,
      drawOnDurationMs: (metadata.default as { drawOnDurationMs: number }).drawOnDurationMs,
    };
  },
  [CrazyEvent.Wormhole]: async () => {
    const [icon, annotation, metadata] = await Promise.all([
      import('./wormhole.svg?raw'),
      import('./wormhole.annotation.svg?raw'),
      import('./wormhole.metadata.json'),
    ]);
    return {
      icon: icon.default,
      annotation: annotation.default,
      drawOnDurationMs: (metadata.default as { drawOnDurationMs: number }).drawOnDurationMs,
    };
  },
  [CrazyEvent.Demotion]: async () => {
    const [icon, annotation, metadata] = await Promise.all([
      import('./demotion.svg?raw'),
      import('./demotion.annotation.svg?raw'),
      import('./demotion.metadata.json'),
    ]);
    return {
      icon: icon.default,
      annotation: annotation.default,
      drawOnDurationMs: (metadata.default as { drawOnDurationMs: number }).drawOnDurationMs,
    };
  },
  [CrazyEvent.TimeBomb]: async () => {
    const [icon, annotation, metadata] = await Promise.all([
      import('./time-bomb.svg?raw'),
      import('./time-bomb.annotation.svg?raw'),
      import('./time-bomb.metadata.json'),
    ]);
    return {
      icon: icon.default,
      annotation: annotation.default,
      drawOnDurationMs: (metadata.default as { drawOnDurationMs: number }).drawOnDurationMs,
    };
  },
  [CrazyEvent.ForcedMarch]: async () => {
    const [icon, annotation, metadata] = await Promise.all([
      import('./forced-march.svg?raw'),
      import('./forced-march.annotation.svg?raw'),
      import('./forced-march.metadata.json'),
    ]);
    return {
      icon: icon.default,
      annotation: annotation.default,
      drawOnDurationMs: (metadata.default as { drawOnDurationMs: number }).drawOnDurationMs,
    };
  },
  [CrazyEvent.Ricochet]: async () => {
    const [icon, annotation, metadata] = await Promise.all([
      import('./ricochet.svg?raw'),
      import('./ricochet.annotation.svg?raw'),
      import('./ricochet.metadata.json'),
    ]);
    return {
      icon: icon.default,
      annotation: annotation.default,
      drawOnDurationMs: (metadata.default as { drawOnDurationMs: number }).drawOnDurationMs,
    };
  },
  [CrazyEvent.CrownThief]: async () => {
    const [icon, annotation, metadata] = await Promise.all([
      import('./crown-thief.svg?raw'),
      import('./crown-thief.annotation.svg?raw'),
      import('./crown-thief.metadata.json'),
    ]);
    return {
      icon: icon.default,
      annotation: annotation.default,
      drawOnDurationMs: (metadata.default as { drawOnDurationMs: number }).drawOnDurationMs,
    };
  },
  [CrazyEvent.Stampede]: async () => {
    const [icon, annotation, metadata] = await Promise.all([
      import('./stampede.svg?raw'),
      import('./stampede.annotation.svg?raw'),
      import('./stampede.metadata.json'),
    ]);
    return {
      icon: icon.default,
      annotation: annotation.default,
      drawOnDurationMs: (metadata.default as { drawOnDurationMs: number }).drawOnDurationMs,
    };
  },
  [CrazyEvent.TollRoad]: async () => {
    const [icon, annotation, metadata] = await Promise.all([
      import('./toll-road.svg?raw'),
      import('./toll-road.annotation.svg?raw'),
      import('./toll-road.metadata.json'),
    ]);
    return {
      icon: icon.default,
      annotation: annotation.default,
      drawOnDurationMs: (metadata.default as { drawOnDurationMs: number }).drawOnDurationMs,
    };
  },
  [CrazyEvent.SwapMeet]: async () => {
    const [icon, annotation, metadata] = await Promise.all([
      import('./swap-meet.svg?raw'),
      import('./swap-meet.annotation.svg?raw'),
      import('./swap-meet.metadata.json'),
    ]);
    return {
      icon: icon.default,
      annotation: annotation.default,
      drawOnDurationMs: (metadata.default as { drawOnDurationMs: number }).drawOnDurationMs,
    };
  },
  [CrazyEvent.RoyalDecree]: async () => {
    const [icon, annotation, metadata] = await Promise.all([
      import('./royal-decree.svg?raw'),
      import('./royal-decree.annotation.svg?raw'),
      import('./royal-decree.metadata.json'),
    ]);
    return {
      icon: icon.default,
      annotation: annotation.default,
      drawOnDurationMs: (metadata.default as { drawOnDurationMs: number }).drawOnDurationMs,
    };
  },
  [CrazyEvent.Backfire]: async () => {
    const [icon, annotation, metadata] = await Promise.all([
      import('./backfire.svg?raw'),
      import('./backfire.annotation.svg?raw'),
      import('./backfire.metadata.json'),
    ]);
    return {
      icon: icon.default,
      annotation: annotation.default,
      drawOnDurationMs: (metadata.default as { drawOnDurationMs: number }).drawOnDurationMs,
    };
  },
  [CrazyEvent.Sentry]: async () => {
    const [icon, annotation, metadata] = await Promise.all([
      import('./sentry.svg?raw'),
      import('./sentry.annotation.svg?raw'),
      import('./sentry.metadata.json'),
    ]);
    return {
      icon: icon.default,
      annotation: annotation.default,
      drawOnDurationMs: (metadata.default as { drawOnDurationMs: number }).drawOnDurationMs,
    };
  },
  [CrazyEvent.RushHour]: async () => {
    const [icon, annotation, metadata] = await Promise.all([
      import('./rush-hour.svg?raw'),
      import('./rush-hour.annotation.svg?raw'),
      import('./rush-hour.metadata.json'),
    ]);
    return {
      icon: icon.default,
      annotation: annotation.default,
      drawOnDurationMs: (metadata.default as { drawOnDurationMs: number }).drawOnDurationMs,
    };
  },
  [CrazyEvent.Haunted]: async () => {
    const [icon, annotation, metadata] = await Promise.all([
      import('./haunted.svg?raw'),
      import('./haunted.annotation.svg?raw'),
      import('./haunted.metadata.json'),
    ]);
    return {
      icon: icon.default,
      annotation: annotation.default,
      drawOnDurationMs: (metadata.default as { drawOnDurationMs: number }).drawOnDurationMs,
    };
  },
  [CrazyEvent.Sacrifice]: async () => {
    const [icon, annotation, metadata] = await Promise.all([
      import('./sacrifice.svg?raw'),
      import('./sacrifice.annotation.svg?raw'),
      import('./sacrifice.metadata.json'),
    ]);
    return {
      icon: icon.default,
      annotation: annotation.default,
      drawOnDurationMs: (metadata.default as { drawOnDurationMs: number }).drawOnDurationMs,
    };
  },
  [CrazyEvent.ShrinkingBoard]: async () => {
    const [icon, annotation, metadata] = await Promise.all([
      import('./shrinking-board.svg?raw'),
      import('./shrinking-board.annotation.svg?raw'),
      import('./shrinking-board.metadata.json'),
    ]);
    return {
      icon: icon.default,
      annotation: annotation.default,
      drawOnDurationMs: (metadata.default as { drawOnDurationMs: number }).drawOnDurationMs,
    };
  },
  [CrazyEvent.DoubleTrouble]: async () => {
    const [icon, annotation, metadata] = await Promise.all([
      import('./double-trouble.svg?raw'),
      import('./double-trouble.annotation.svg?raw'),
      import('./double-trouble.metadata.json'),
    ]);
    return {
      icon: icon.default,
      annotation: annotation.default,
      drawOnDurationMs: (metadata.default as { drawOnDurationMs: number }).drawOnDurationMs,
    };
  },
};
